apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: su2qr3kwv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: su2qr3kwv-nodejs 
  name: su2qr3kwv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: su2qr3kwv-nodejs 
